MATERIAL_KEYS = (
    "name",
    "color",
    "metalness",
    "specularColor",
    "roughness",
    "ior",
    "complexIor",
    "density",
    "category",
    "description",
    "sources",
    "tags",
    "reference"
)

PBR_NODE_INPUTS = (
    "Alpha",
    "Anisotropic",
    "Anisotropic Rotation",
    "Base Color",
    "Clearcoat",
    "Clearcoat Normal",
    "Clearcoat Roughness",
    "Emission",
    "Emission Strength",
    "IOR",
    "Metallic",
    "Normal",
    "Roughness",
    "Sheen",
    "Sheen Tint",
    "Specular",
    "Specular Tint",
    "Subsurface",
    "Subsurface Anisotropy",
    "Subsurface Color",
    "Subsurface IOR",
    "Subsurface Radius",
    "Tangent",
    "Transmission",
    "Transmission Roughness",
    "Weight",
)

